import 'dart:convert';
import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';

/// Real file exports: CSV writing + sharing, and a readable PDF summary.
/// Nothing is simulated — files are written to the temp directory and shared
/// through the platform share sheet (mobile) or download (web).
class ExportService {
  ExportService._();

  static Future<Directory> _dir() async {
    if (kIsWeb) {
      throw UnsupportedError('File export uses the share sheet on this platform.');
    }
    return getTemporaryDirectory();
  }

  static Future<String> writeCsv(
    String filename,
    List<String> headers,
    List<List<String>> rows,
  ) async {
    final dir = await _dir();
    final buf = StringBuffer();
    String esc(String s) =>
        s.contains(',') || s.contains('"') || s.contains('\n')
            ? '"${s.replaceAll('"', '""')}"'
            : s;
    buf.writeln(headers.map(esc).join(','));
    for (final r in rows) {
      buf.writeln(r.map(esc).join(','));
    }
    final file = File('${dir.path}/$filename');
    await file.writeAsString(buf.toString(), encoding: utf8);
    return file.path;
  }

  static Future<String> writeTextFile(
      String filename, String content) async {
    final dir = await _dir();
    final file = File('${dir.path}/$filename');
    await file.writeAsString(content, encoding: utf8);
    return file.path;
  }

  static Future<void> shareFile(String path, {String subject = 'Bloom export'}) async {
    if (kIsWeb) {
      await Share.shareXFiles([XFile(path)], subject: subject);
      return;
    }
    final file = File(path);
    if (!await file.exists()) {
      throw StateError('Export file not found: $path');
    }
    await Share.shareXFiles([XFile(path)], subject: subject);
  }

  /// Builds a readable one-page-ish PDF summary of the user's recent data.
  static Future<String> buildSummaryPdf({
    required String title,
    required List<(String, String)> facts,
    required String generatedNote,
  }) async {
    final doc = pw.Document();
    doc.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (ctx) => pw.Padding(
          padding: const pw.EdgeInsets.all(32),
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(title,
                  style: pw.TextStyle(
                      fontSize: 26, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 8),
              pw.Text(generatedNote,
                  style: const pw.TextStyle(fontSize: 11, color: PdfColors.grey700)),
              pw.SizedBox(height: 24),
              ...facts.map((f) => pw.Padding(
                    padding: const pw.EdgeInsets.only(bottom: 10),
                    child: pw.Row(
                      crossAxisAlignment: pw.CrossAxisAlignment.start,
                      children: [
                        pw.Expanded(
                          flex: 2,
                          child: pw.Text(f.$1,
                              style: pw.TextStyle(
                                  fontSize: 13,
                                  fontWeight: pw.FontWeight.bold)),
                        ),
                        pw.Expanded(
                          flex: 3,
                          child: pw.Text(f.$2,
                              style: const pw.TextStyle(fontSize: 13)),
                        ),
                      ],
                    ),
                  )),
              pw.Spacer(),
              pw.Text(
                'Generated by Bloom on this device. Trends are computed from your saved records; correlations do not prove causes.',
                style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
              ),
            ],
          ),
        ),
      ),
    );
    final dir = await _dir();
    final file = File(
        '${dir.path}/bloom-summary-${DateTime.now().millisecondsSinceEpoch}.pdf');
    await file.writeAsBytes(await doc.save());
    return file.path;
  }
}
